### ISSUE TITLE
Add Brightness Control to API

### ISSUE THREAD

**Issue by jpk6789** [patrick-dmxc/NanoleafAPI#1]
The controller / Tiles NL42 have a brightness sensor. There is a setting to control the brightness range in which the Nanoleafs can opperate automatically according to the environment brightness. This confic should be editable.

Commands:
{"write":{"command":"requestBrightnessSensorConfig"}}

{"write":{"command":"setBrightnessSensorConfig","brightnessSensorConfig":{"enabled":true,"brightnessSensorMode":1,"userMinBrightness":3,"userMaxBrightness":100}}}

Response:
{"brightnessSensorConfig":{"enabled":true,"brightnessSensorMode":1,"userMaxBrightness":100,"userMinBrightness":1,"isCalibrated":true,"isCalibrating":false}}

**Comment by patrick-dmxc** [comment]
What modes are there?
So which number stands for which mode
